name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: |
        echo "== Installing required packages =="
        sudo apt-get update
        sudo apt-get install -y golang-go p7zip-full yarn nodejs
        echo "== Installing Ultralight libraries"
        wget https://ultralight-sdk.sfo2.cdn.digitaloceanspaces.com/ultralight-sdk-latest-linux-x64.7z
        7z x ultralight-sdk-latest-linux-x64.7z bin
    - name: Build frontend
      run: |
        cd public
        yarn
        cd ..
        go generate
    - name: Build the actual program
      run: |
        env LD_LIBRARY_PATH=./bin go build
        
       
